version: '3'
services:
  flask-app:
    build: .
    environment:
      FLASK_APP: app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - flask-postgres-network

networks:
  flask-postgres-network:
    external: true  # 이미 존재하는 네트워크를 사용

volumes:
  postgres_data:
    external: true
